version: "3.9"

services:
  kasmvnc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Ergocub_simulation_full_desktop
    ports:
      - "6901:6901" # KasmVNC
      - "11345:11345"
      - "11346:11346"
      - "11347:11347"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Prague
      - VNC_PW=password
    volumes:
      - ./config:/config
      - ./gazebo_models:/usr/share/gazebo/models
    restart: unless-stopped


