version: "3.9"

services:
  simulation:

    build:
      context: .
      dockerfile: simulation_container/Dockerfile
    container_name: Ergocub_simulation

    ports:
      - "6901:6901" # KasmVNC
      - "10000:10000" # YARP server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Prague
      - VNC_PW=password
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ./simulation_container/yarp-ros2-ergocub-bridging/:/opt/yarp-ros2-ergocub-bridging/
      - ./simulation_container/python/:/opt/code/
      - ./gazebo_models:/usr/share/gazebo/models
      - ./simulation_container/ergocub_modified/:/opt/robotology-superbuild/build-base/install/share/ergoCub/robots/ergocub_modified
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

networks:
  sim-control-network:
    driver: bridge



